# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
---
# BlueBuild Recipe for CentOS Stream 9 - Lenovo AMD Laptops
# Target: Lenovo IdeaPad 5 15ALC05 (AMD Ryzen 5500U)
# DE: KDE Plasma 5.27 LTS (from EPEL 9)
#
# Build: bluebuild build ./recipes/recipe.yml

name: centos9-ideapad5-plasma
description: CentOS Stream 9 KDE Plasma Desktop for Lenovo IdeaPad 5 15ALC05

base-image: quay.io/centos-bootc/centos-bootc
image-version: stream9

modules:
  # ========================================
  # BASE SYSTEM
  # ========================================
  - from-file: base-repos.yml

  - from-file: base-system.yml

  - from-file: hardware-amd-laptop.yml

  - from-file: networking.yml

  - from-file: audio-pipewire.yml

  - from-file: power-management.yml

  # ========================================
  # DESKTOP ENVIRONMENT - KDE Plasma
  # Available options for CentOS Stream 9:
  #   desktop-plasma-fixed.yml  <- KDE Plasma 5.27 (EPEL 9) - CURRENT
  #   desktop-gnome-fixed.yml   <- GNOME 40 (base repos)
  #   desktop-xfce-fixed.yml    <- XFCE (EPEL 9) - lightweight
  # ========================================
  - from-file: desktop-plasma-fixed.yml

  # ========================================
  # APPLICATIONS & TOOLS
  # ========================================
  - from-file: apps-browser.yml

  - from-file: apps-containers.yml

  - from-file: apps-server.yml

  # Optional - comment out if not needed
  - from-file: apps-dev.yml

  # ========================================
  # FINAL CONFIGURATION
  # ========================================
  - from-file: system-config.yml
